[package]
name = "test_pcl_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "test_pcl_rs"

[dependencies]
ros_pointcloud2 = "0.4.0"
pcl_rs = { path = "../../" }